### ISSUE TITLE
No type named 'MserFeatureDetector' in namespace 'cv'

### ISSUE THREAD

**Issue by takasurazeem** [NeilNie/Object_Tracking#1]
While trying to run the iOS Application project I am getting the following error in the file MSERManager.mm
I am using the latest version of opencv and Xcode 9.2
`No type named 'MserFeatureDetector' in namespace 'cv'`
Line # 28 as of 39th commit of the project.

**Comment by NeilNie** [comment]
thanks for raising the issue, I will try to look into it.

**Comment by NeilNie** [comment]
Please download the latest release of OpenCV 2. The project doesn't support OpenCV 3.x yet. Here is the link: [https://sourceforge.net/projects/opencvlibrary/files/opencv-ios/2.4.13/](https://sourceforge.net/projects/opencvlibrary/files/opencv-ios/2.4.13/)
